# Generated by Django 5.0.1 on 2024-01-26 23:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_remove_customuser_amizade_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="amizade_id",
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
